# Generated by Django 5.0.3 on 2024-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='time',
            field=models.TimeField(max_length=50, null=True),
        ),
    ]
